# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'transport_reality_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'HEREMaps'
  pod 'RealmSwift'
  pod 'SnapKit', '~> 4.0'
  # Pods for transport_reality_app

end
